version: "3.4"

services:
  promocao-humana:
    container_name: promocao-humana
    image: promocao-humana
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile